version: '3.5'
services: 
  ng-service: 
    container_name: ng-container
    build: ./
    volumes: 
      - './:/usr/src/app'
    ports:
      - '4200:4200'
    command: > 
      bash -c "ng serve --host 0.0.0.0 --port 4200"